global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'scraper_service'
    static_configs:
      - targets: ['scraper_service:8001']

  - job_name: 'job_service'
    static_configs:
      - targets: ['job_service:4000']

  - job_name: 'publish_service'
    static_configs:
      - targets: ['publish_service:4010']
 
