"""create jobs table

Revision ID: 738614f0d5c9
Revises: 
Create Date: 2025-03-09 02:51:52.498025

"""
from typing import Sequence, Union

from alembic import op
import os


# revision identifiers, used by Alembic.
revision: str = '738614f0d5c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sql_content = """
    CREATE TABLE IF NOT EXISTS jobs (
        job_id SERIAL PRIMARY KEY,
        job_title character varying(255),
        company_name character varying(255),
        industry character varying(255),
        job_exp character varying(50),
        job_desc TEXT,
        job_info JSONB,
        job_condition TEXT,
        job_salary character varying(255),
        people character varying(50),
        place character varying(255),
        update_date DATE,
        record_time TIMESTAMP WITH TIME ZONE,
        source character varying(50),
        keywords character varying(255),
        job_link character varying(1024) UNIQUE
    );
    """

    if sql_content:
        # 如果有提供 SQL 內容，執行該內容
        op.execute(sql_content)
    else:
        # 如果沒有 SQL 內容，則根據檔案位置執行 SQL 文件
        sql_file_path = os.path.join(
            os.path.dirname(__file__),  # 當前文件目錄
            '../../../postgres_db/create_jobs.sql'  # 相對於該目錄的路徑
        )

        # 解析為絕對路徑
        sql_file_path = os.path.abspath(sql_file_path)   
             
        with open(sql_file_path, 'r', encoding='utf-8') as sql_file:
            sql_script = sql_file.read()

        # 執行從 SQL 文件讀取的腳本
        op.execute(sql_script)


    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""

    sql_content = """
    DROP TABLE IF EXISTS jobs;
    """
    
    # 執行刪除表格的 SQL
    op.execute(sql_content)