version: '3.8'

services:
  mosquitto:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.mq
    image: yhsintseng/docker_mosquitto:latest
    #沒有創建mosquitto.db就無法離線
    volumes:
      - ./mosquitto/data:/mosquitto/data
    #1883在容器內已被佔用(可能是socket)
    ports:
      - "1884:1884"
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 1884 || exit 1" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: jobs
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d jobs" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  scraper_service:
    # build:
    #   context: ../
    #   dockerfile: Docker/Dockerfile.python
    image: yhsintseng/docker_python:latest
    ##取代資料夾內的.env
    env_file:
      - ./.env
    ports:
      - "5060:5060"
      - "8001:8001"
    ##保存container中的紀錄
    volumes:
      - ./scraper_service/data:/app/scraper_service/data
      - ../postgres_db:/app/postgres_db

  job_service:
    image: yhsintseng/docker_job_service:latest
    # build:
    #   context: ../
    #   dockerfile: Docker/Dockerfile.nodejs_job
    env_file:
      - ./.env
    working_dir: /app
    ports:
      - "4000:4000"
    # container_name: job_service
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  publish_service:
    # build:
    #   context: ../
    #   dockerfile: Docker/Dockerfile.nodejs_pub
    image: yhsintseng/docker_publish_service:latest
    env_file:
      - ./.env
    working_dir: /app
    ports:
      - "4010:4010"

  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://test:test@postgres:5432/jobs?sslmode=disable"
    ports:
      - "9187:9187"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitor/data/prometheus:/prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "4050:4050"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
    volumes:
      - ./monitor/data/grafana:/var/lib/grafana
      - "./monitor/config/grafana.ini:/etc/grafana/grafana.ini"
