# 使用官方 Node.js image作為基礎
FROM node:alpine

# 設定工作目錄
WORKDIR /app

# 複製 Node.js 應用程式代碼
COPY node_app/job_service /app
COPY node_app/commons /app 

# 安裝 Node.js 依賴
RUN npm install

# 設定預設命令
CMD ["node", "server.js"]
