# 使用官方 Python image作為基礎
FROM python:latest

# 設定工作目錄
WORKDIR /app

# 安裝 Poetry
RUN pip install poetry

# 複製 Python 應用程式程式碼
COPY ../scraper_service /app

# 刪除可能不需要的檔案或目錄(以免報錯)
RUN rm -rf /app/.venv/

# 安裝 Python 依賴
RUN poetry install

# 設定預設命令
CMD ["poetry", "run", "python", "main.py"]
