# 使用官方 Python image作為基礎
FROM python:3.9.7 

# 設定工作目錄
WORKDIR /app/scraper_service

# 安裝 Poetry
RUN pip install --no-cache-dir poetry

# 複製 Python 應用程式程式碼
COPY ../scraper_service /app/scraper_service

# 安裝 Python 依賴
RUN poetry install --no-dev

# 設定預設命令
CMD ["poetry", "run", "python", "main.py"]
