[tool.poetry]
name = "scraper-service"
version = "0.1.0"
description = ""
authors = ["easontseng <yhsints@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^3.1.0"
requests = "^2.32.3"
bs4 = "^0.0.2"
psycopg2-binary = "^2.9.10"
dotenv = "^0.9.9"
pytz = "^2025.1"
pydantic = "^2.10.6"
schedule = "^1.2.2"
alembic = "^1.15.1"
flask-cors = "^5.0.1"
prometheus-client = "^0.21.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
